CREATE TYPE "wallet_status" AS ENUM (
  'enabled',
  'disabled'
);

CREATE TYPE "transaction_status" AS ENUM (
  'success',
  'failed'
);

CREATE TYPE "transaction_type" AS ENUM (
  'withdraw',
  'deposit'
);

CREATE TABLE "user_token" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid UNIQUE,
  "token" varchar(42) UNIQUE,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "wallet" (
  "id" uuid PRIMARY KEY,
  "user_id" uuid UNIQUE,
  "status" wallet_status,
  "enabled_at" timestamp,
  "balance" float
);

CREATE TABLE "transactions" (
  "id" uuid PRIMARY KEY,
  "wallet_id" uuid,
  "status" transaction_status,
  "transacted_at" timestamp DEFAULT (now()),
  "type" transaction_type,
  "amount" float,
  "reference_id" uuid UNIQUE
);

CREATE UNIQUE INDEX ON "wallet" ("id", "user_id");

ALTER TABLE "wallet" ADD FOREIGN KEY ("user_id") REFERENCES "user_token" ("user_id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("wallet_id") REFERENCES "wallet" ("id");
